### ISSUE TITLE
How make something like this on the default template of the blog 

### ISSUE THREAD

**Issue by heyjumanji** [jktrn/enscribe.dev-v2#4]
I want to make the link post something like this but the post dont show up the banners ?? Can you help me!
![IMG_20240424_190236](https://github.com/jktrn/enscribe.dev/assets/90971841/5f1f36c6-1ac6-484b-a94f-7d74a5de8533)

**Comment by jktrn** [comment]
@heyjumanji Hey! Sorry, I didn't see this. You can do this via the [Open Graph Protocol](https://ogp.me/), in particular the `og:image` tag. You can specify this in your `<head>`:

```html
<meta property="og:image" content="https://enscribe.dev//static/images/picoctf-2022/beginners-compilation/banner.webp">
```

Twitter also has its own metadata protocol:

```html
<meta name="twitter:image" content="https://enscribe.dev/static/images/picoctf-2022/beginners-compilation/banner.webp">
```
